name: ZeroWaste

attributes:
  ORGANIZATIONNAME: Depromeet

options:
  deploymentTarget:
    iOS: 14.0
  defaultConfig: Release
  indentWidth: 4
  tabWidth: 4
    
  postGenCommand: pod install

targets:
  ZeroWaste:
      type: application
      platform: iOS
      settings:
        base:
          INFOPLIST_FILE: ZeroWaste/Supporting/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: Depromeet.ZeroWaste
      sources: [ZeroWaste]

  ZeroWasteTests:
      type: bundle.unit-test
      platform: iOS
      settings:
        base:
          INFOPLIST_FILE: ZeroWasteTests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: Depromeet.ZeroWasteTests
      sources: [ZeroWasteTests]

  ZeroWasteUITests:
      type: bundle.ui-testing
      platform: iOS
      settings:
        base:
          INFOPLIST_FILE: ZeroWasteUITests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: Depromeet.ZeroWasteUITests
      sources: [ZeroWasteUITests]